# https://nx.dev/more-concepts/folder-structure
# https://pnpm.io/workspaces
packages:
  - "**/client/"
  - "**/server/"
  - "**/types/"

catalog: 
  typescript: ^5.5.4
  '@types/node': ^20.14.12
  # FiveM  
  '@citizenfx/client': 2.0.9282-1
  '@citizenfx/server': 2.0.9282-1
  # Bundle
  rollup: ^4.20.0
  tslib: ^2.6.3
  '@rollup/plugin-commonjs': ^26.0.1
  '@rollup/plugin-node-resolve': ^15.2.3
  '@rollup/plugin-typescript': ^11.1.6
  fast-glob: "^3.3.2" #Used to detech all entry files
